### PR TITLE
upgrade google analytics call

### PR DESCRIPTION
**Pull request by andreagenso**
Upgrade Google Analytics to the last way, based on Google instructions:

*  ga.js is deprecated , replaced by  analytics.js 
*  analytics.js  is deprecated, replaced by google tag manager.

i this upgrade we are using the call focus to GTM (recommended by google).

### CODE REVIEW

**Review by d6y — APPROVED** [review]
LGTM! Thank you!

**Comment by d6y** [comment]
Thank you for this @andreagenso  🎉 

It's not yet published because of #9, but I'll sort that out tomorrow (it's late where I am at the moment).

**Comment by andreagenso** [comment]
Ok, thanks you too :D

**Comment by d6y** [comment]
@andreagenso OK, that's now been published as....

```
 "net.liftmodules" %% "google-analytics_3.2" % "1.2.0-SNAPSHOT"
```

Note that I'm bumped the version number to 1.2.0.  Let me know if that works for you... if it does, I'll publish a non-SNAPSHOP version.

**Comment by andreagenso** [comment]
Ok, Richard, I am checking now, thank you very much!!

**Comment by andreagenso** [comment]
@d6y  all is working very well!!  , please  Can you  publish the non-SNAPSHOP version ?.  :dancer:  :D

**Comment by d6y** [comment]
Thanks for letting me know. The release is happening. Give it 2-4 hours: https://github.com/d6y/liftmodules-googleanalytics/releases/tag/3.2-1.2.0-release

**Comment by andreagenso** [comment]
Ok, great!, thanks a lot! :D

**Pull request merged**
